/* Agent 对话浏览器验收，只使用合成模型和 COS 替身。 */
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const {chromium} = require('playwright');
(async () => {
  const output = '/tmp/fileaction-agent-browser'; await fs.mkdir(output,{recursive:true});
  const browser = await chromium.launch({channel:'chrome',headless:true});
  const page = await browser.newPage({viewport:{width:1440,height:1050},acceptDownloads:true});
  page.setDefaultTimeout(15000);
  const errors=[], calls=[];
  page.on('pageerror',e=>errors.push(e.message));
  page.on('request',r=>{if(r.url().endsWith('/api/chat'))calls.push(r.postDataJSON());});
  const ready=()=>page.waitForFunction(()=>!document.body.classList.contains('busy'));
  const turns=async(n)=>{await page.locator('.assistant-message').nth(n-1).waitFor();await ready();};
  const send=async(message,n)=>{await page.locator('#chat-input').fill(message);await page.locator('#chat-send').click();await turns(n);};
  const end=async()=>{await ready();await page.locator('#finish').click();await page.locator('#welcome').waitFor({state:'visible'});};
  const sample=async()=>{await page.locator('#upload-consent').check();await page.locator('#sample').click();await turns(1);};
  try {
    await page.goto('http://127.0.0.1:8791/');
    await page.locator('#sample').click();await page.locator('#workspace').waitFor({state:'visible'});await ready();
    await page.locator('#send-consent').check();await page.locator('#analyze').click();
    await page.locator('#settings-dialog').waitFor({state:'visible'});
    assert.equal(await page.locator('.assistant-message').count(),0);
    await page.locator('[data-close="settings-dialog"]').click();await end();
    console.log('PASS 未配置模型时显式提示，不生成假结果');

    await page.goto('http://127.0.0.1:8790/');
    await page.getByText(/合成HTTP测试替身（非真实LLM） · 已配置/).waitFor();
    await page.locator('#sample').click();await page.locator('#workspace').waitFor({state:'visible'});await ready();
    assert.equal(await page.locator('#agent-thread').count(),1);
    assert.equal(await page.locator('#background').count(),0);
    assert.equal(await page.locator('.steps').count(),0);
    assert.equal(await page.locator('.assistant-message').count(),0);
    assert.equal(calls.length,0);
    await page.locator('#analyze').click();assert.match(await page.locator('#notice').textContent(),/请先确认/);
    console.log('PASS 上传直接进入 Agent，未授权不外发，不先收集资料');
    await page.locator('#send-consent').check();await page.locator('#analyze').click();await turns(1);
    assert.equal(calls[0].message,'');
    assert.match(await page.locator('.file-summary').textContent(),/奖学金/);
    assert.match(await page.locator('.positioning').textContent(),/猜测.*待你确认/);
    assert.equal(await page.locator('#memory-count').textContent(),'0');
    assert.equal(await page.locator('#action-section').isVisible(),false);
    await page.locator('.insight-details').first().locator('summary').click();
    await page.locator('.evidence').first().click();assert.equal(await page.locator('.source-line.highlight').count(),1);
    await page.screenshot({path:output+'/first-summary.png',fullPage:true});
    await page.locator('.end-chat').last().click();await page.locator('#welcome').waitFor({state:'visible'});
    console.log('PASS 没有沉淀也先总结、定位仅猜测、引用可核对、无需回答就能退出');

    await sample();assert.equal(await page.locator('#agent-start').isVisible(),false);
    await send('合成背景：我是老师，想把通知转发给学生',2);
    assert.match(await page.locator('.assistant-message').last().textContent(),/你是老师/);
    assert.equal(await page.locator('.assistant-message').last().locator('.positioning').count(),0);
    assert.equal(await page.locator('#memory-count').textContent(),'0');
    await page.locator('.skip-questions').last().click();await turns(3);
    assert.equal(await page.locator('.assistant-message').last().locator('.agent-question').count(),0);
    console.log('PASS 自动首轮输出、连续对话、纠正定位、可跳过询问且不自动保存');
    await page.locator('.action-choice').last().click();await page.locator('#action-section').waitFor({state:'visible'});
    await page.locator('#generate').click();assert.match(await page.locator('#notice').textContent(),/请先确认/);
    await page.locator('#action-confirm').check();await page.locator('#generate').click();
    await page.locator('#draft-section').waitFor({state:'visible'});await ready();
    assert.match(await page.locator('#draft').inputValue(),/教师转发视角/);
    await page.locator('#draft').fill((await page.locator('#draft').inputValue())+'\n合成编辑验收补充');
    const downloaded=page.waitForEvent('download');await page.locator('#export-draft').click();
    const download=await downloaded;await download.saveAs(output+'/edited.md');
    assert.match(await fs.readFile(output+'/edited.md','utf8'),/合成编辑验收补充/);
    console.log('PASS 产物入口按对话展开、确认后生成、使用对话身份、编辑导出');

    await page.locator('.storage-details summary').click();await page.locator('#store-original').click();
    assert.match(await page.locator('#notice').textContent(),/请先确认/);
    await page.locator('#cos-consent').check();await page.locator('#store-original').click();await ready();
    assert.match(await page.locator('#cos-file-state').textContent(),/已保存到 COS/);
    page.once('dialog',d=>d.accept());await page.locator('#store-draft').click();await ready();
    await page.locator('#files-open').click();await page.locator('#files-dialog').waitFor({state:'visible'});
    assert.equal(await page.locator('#files-list .memory-entry').count(),2);
    await page.getByRole('button',{name:'打开',exact:true}).last().click();await page.locator('#files-dialog').waitFor({state:'hidden'});
    assert.equal(await page.locator('.assistant-message').count(),0);
    await page.locator('#files-open').click();
    page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'删除云端文件',exact:true}).first().click();
    await page.waitForFunction(()=>document.querySelectorAll('#files-list .memory-entry').length===1);
    page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'删除云端文件',exact:true}).first().click();
    await page.waitForFunction(()=>document.querySelectorAll('#files-list .memory-entry').length===0);
    await page.locator('[data-close="files-dialog"]').click();await end();
    console.log('PASS COS 单独授权、原文件与产物保存、打开及删除（SDK 替身）');

    await page.locator('#memory-open').click();await page.locator('#add-memory').click();
    await page.locator('#memory-content').fill('合成用户是一名老师');await page.locator('#memory-consent').check();
    await page.getByRole('button',{name:'确认保存到本机',exact:true}).click();
    await page.locator('#edit-memory-dialog').waitFor({state:'hidden'});
    await page.locator('[data-close="memory-dialog"]').click();await sample();
    assert.match(await page.locator('#snapshot-note').textContent(),/1 条/);
    await page.locator('.insight-details').last().locator('summary').click();
    assert.match(await page.locator('.insight').last().textContent(),/合成用户是一名老师/);
    await send('我暂时不需要继续',2);
    assert.equal(await page.locator('.assistant-message').last().locator('.agent-question,.action-choice').count(),0);
    await end();
    await page.locator('#memory-open').click();page.once('dialog',d=>d.accept());
    await page.locator('#memory-list').getByRole('button',{name:'删除',exact:true}).click();
    await page.waitForFunction(()=>document.querySelector('#memory-count').textContent==='0');
    await page.locator('[data-close="memory-dialog"]').click();
    console.log('PASS 有沉淀首轮即结合，退出意图不再索取信息，长期保存和删除均确认');

    await sample();await page.locator('#chat-input').fill('无效引用合成测试');await page.locator('#chat-send').click();await ready();
    assert.match(await page.locator('#notice').textContent(),/引用校验失败/);
    assert.equal(await page.locator('.assistant-message').count(),1);
    assert.equal(await page.locator('#retry-chat').isVisible(),true);await end();
    await sample();await page.locator('#chat-input').fill('延迟合成测试');await page.locator('#chat-send').click();
    await page.locator('#cancel').click();await ready();await page.waitForTimeout(3300);
    assert.equal(await page.locator('.assistant-message').count(),1);await end();
    console.log('PASS 对话引用错误显式失败、取消不会展示迟到回复');

    await page.locator('#upload-consent').check();
    await page.locator('#upload').setInputFiles({name:'合成采购.txt',mimeType:'text/plain',buffer:Buffer.from('合成采购事项\n采购需要核对数量和供应商交付日期。')});await turns(1);
    assert.match(await page.locator('.file-summary').textContent(),/采购/);
    assert.match(await page.locator('.agent-question').textContent(),/采购/);
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
    await page.screenshot({path:output+'/mobile.png',fullPage:true});await end();
    await page.locator('#upload').setInputFiles({name:'合成.exe',mimeType:'application/octet-stream',buffer:Buffer.from('synthetic')});await ready();
    assert.match(await page.locator('#notice').textContent(),/暂时支持/);
    assert.deepEqual(errors,[]);
    console.log('PASS 文件类型决定不同问题、移动布局、格式失败和无脚本错误');
  } finally {await browser.close();}
})().catch(e=>{console.error(e.message);process.exit(1)});
