/* 真实模型交互验收：仅合成档案和通知，会实际消耗模型额度。 */
const assert=require('node:assert/strict'),fs=require('node:fs/promises');const {chromium}=require('playwright');
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});const p=await b.newPage({viewport:{width:1440,height:1000}});p.setDefaultTimeout(115000);const report={time:new Date().toISOString(),synthetic_data:true,real_model:true,scenarios:[]};const owned=[];const ready=()=>p.waitForFunction(()=>!document.body.classList.contains('busy'));const errors=[];p.on('pageerror',e=>errors.push(e.message));
const request=async(path,data)=>p.evaluate(async({path,data})=>{const headers={'Content-Type':'application/json','X-FileAction-Token':document.querySelector('meta[name="fileaction-token"]').content};const r=await fetch(path,{headers,...(data===undefined?{}:{method:'POST',body:JSON.stringify(data)})});const value=await r.json();if(!r.ok)throw Error(value.error);return value},{path,data});
const notification='合成比赛通知，学校、赛事和人物均虚构。\n星河大学开放创意设计赛\n面向在校本科生，1至3人同校组队。\n主视觉赛道需提交三张原创海报和设计说明；产品界面赛道需提交可交互界面原型与产品说明。\n报名截止：2026年11月30日17:00（北京时间）。\n报名链接：https://example.com/synthetic-contest\n须本人核实学籍与作品原创性；准备材料不代表报名成功。';
try{await p.goto('http://127.0.0.1:8792/');let memory=await request('/api/memory');assert.equal(memory.entries.length,0);const status=await request('/api/status');report.model=status.model;
const add=await request('/api/memory',{action:'add',target:'user',content:'合成用户：星河大学大二计算机专业本科生，近期做了小程序，没有视觉设计作品，想判断这次比赛是否值得投入。',consent:true});const entry=add.entries[0];
for(const role of ['student','teacher']){
if(role==='teacher'){memory=await request('/api/memory');await request('/api/memory',{action:'replace',target:'user',entry_id:entry.id,content:'合成修正：我是高校教师，负责向学生转发赛事通知，不打算自己参赛，希望整理学生最需要注意的报名和提交要求。',consent:true,expected_revision:memory.revision});await p.locator('#finish').click();await p.locator('#welcome').waitFor({state:'visible'});}
await p.locator('#upload-consent').check();await p.locator('#persist-consent').uncheck();const start=Date.now();await p.locator('#upload').setInputFiles({name:`合成针对性验收-${role}-${Date.now()}.txt`,mimeType:'text/plain',buffer:Buffer.from(notification+(role==='teacher'?'\n此为合成教师阅读场景。':''))});
await p.waitForFunction(()=>document.querySelector('.stream-text')?.textContent || (!document.body.classList.contains('busy') && document.querySelector('#notice').classList.contains('error')));
if(await p.locator('#notice').evaluate(n=>n.classList.contains('error')))throw Error(await p.locator('#notice').textContent());const firstSeconds=(Date.now()-start)/1000;await p.locator('.assistant-message').waitFor();await ready();const all=await request('/api/workspaces');const current=all.workspaces[0];owned.push(current.id);const doc=await request('/api/workspace/open',{file_id:current.id});const analysis=doc.analysis;assert.ok(analysis.insights.some(i=>i.memory_refs.includes(entry.id)),'需引用实际用户档案');
assert.equal(await p.locator('.file-summary').isVisible(),false);const main=[analysis.response,analysis.overview,...analysis.insights.map(i=>i.meaning)].join('\n');if(role==='student'){assert.match(main,/计算机|小程序/);assert.match(main,/界面|原型/);}else{assert.match(main,/教师|老师|转发/);assert.doesNotMatch(analysis.questions.join('\n'),/你(?:是否|目前是).*本科/);}
await p.locator('.highlight-source').first().click();await p.locator('#source-dialog').waitFor({state:'visible'});assert.equal(await p.locator('#source-preview .is-target').isVisible(),true);await p.locator('[data-close="source-dialog"]').click();
report.scenarios.push({role,passed:true,first_text_seconds:firstSeconds,complete_seconds:(Date.now()-start)/1000,response:analysis.response,overview:analysis.overview,questions:analysis.questions,profile_id:entry.id,insights:analysis.insights.map(i=>({title:i.title,meaning:i.meaning,memory_refs:i.memory_refs}))});console.log('PASS 真实模型按合成'+role+'档案给出针对性解读');
if(role==='student'){
const button=p.locator('.assistant-message').last().locator('.positioning .clarification-trigger');if(await button.count()){await button.click();await p.locator('#clarification-answer').fill('合成补充：我明确想了解产品界面赛道，正在做小程序界面。请结合我的经历告诉我先补什么，不用重新总结比赛。');await p.locator('#clarification-submit').click();await p.locator('.assistant-message').nth(1).waitFor();await ready();const follow=await request('/api/workspace/open',{file_id:current.id});assert.match(follow.analysis.response+' '+follow.analysis.overview,/界面|小程序/);report.clarification={passed:true,response:follow.analysis.response,profile_card_saved:follow.knowledge.entries.length>0};}
}
}
assert.deepEqual(errors,[]);await p.screenshot({path:'var/live-feedback-synthetic-teacher.png'});await fs.writeFile('var/live-feedback-verification.json',JSON.stringify(report,null,2));console.log(JSON.stringify({model:report.model,passed:report.scenarios.length,clarification:report.clarification?.passed}));
}catch(e){report.error=e.message;report.notice=await p.locator('#notice').textContent();await fs.writeFile('var/live-feedback-failure.json',JSON.stringify(report,null,2));throw e;}finally{for(const id of owned)await request('/api/workspace/delete',{file_id:id,consent:true}).catch(()=>{});await b.close();}})().catch(e=>{console.error(e.message);process.exit(1)});
