// 从仓库根目录运行；PLAYWRIGHT_MODULE 指向本机 Playwright。
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const out = '.planning/2026-10-02-pitch-alignment/verified';
const url = 'http://127.0.0.1:8787/07-宣传页/';
fs.mkdirSync(out, { recursive: true });
(async () => {
  const browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
  const errors = [];
  const watch = page => {
    page.on('pageerror', error => errors.push(error.message));
    page.on('response', r => { if (r.status() >= 400) errors.push(`${r.status()} ${r.url()}`); });
    page.on('request', r => { if (r.method() !== 'GET') errors.push(`非预期请求 ${r.method()} ${r.url()}`); });
  };
  const progress = (page, selector, key) => page.locator(selector).evaluate((e, k) => +e.dataset[k], key);
  const complete = (page, selector, key) => page.waitForFunction(({selector, key}) => ['complete', 'static'].includes(document.querySelector(selector).dataset[key]), {selector, key}, {timeout:10000});
  const enter = (page, selector) => page.evaluate(selector => {
    const r = document.querySelector(selector).getBoundingClientRect();
    scrollTo({top:r.top + scrollY - document.querySelector('.nav-wrap').getBoundingClientRect().bottom - 12, behavior:'instant'});
  }, selector);
  async function noOverflow(page, selector) {
    const bad = await page.locator(selector).evaluate(root => [...root.querySelectorAll('h1,h2,h3,p,button,li:not(.organize-slot),textarea,select,.organize-card strong,.organize-insight b')].filter(e => e.getClientRects().length && e.scrollWidth > e.clientWidth + 2).map(e => `${e.tagName}.${e.className}: ${e.textContent.slice(0,80)}`));
    assert.deepEqual(bad, [], `${selector} 不裁字`);
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), '页面无横向溢出');
  }
  try {
    for (const [width,height] of (process.env.SKIP_LAYOUT ? [] : [[1440,900],[1024,768],[768,1024],[390,844],[320,568]])) {
      const page = await browser.newPage({viewport:{width,height}});
      watch(page);
      await page.goto(url);
      await page.evaluate(() => document.fonts.ready);
      await page.waitForTimeout(150);
      assert.equal(await progress(page,'.opportunity-scene','radarProgress'),0);
      assert.equal(await progress(page,'.action-scene','actionProgress'),0);
      await noOverflow(page,'.hero');
      await page.screenshot({path:`${out}/${width}-hero-final.png`});
      await page.evaluate(() => {
        const s = document.querySelector('.organize-scene');
        scrollTo({top:s.getBoundingClientRect().top + scrollY + parseFloat(s.style.getPropertyValue('--order-scene-height')) - s.querySelector('.organize-sticky').offsetHeight - parseFloat(s.style.getPropertyValue('--order-pin-top')),behavior:'instant'});
      });
      await page.waitForFunction(() => document.querySelector('.organize-scene').dataset.organizeState === 'ordered');
      assert.equal(await page.locator('[data-reading-focus="true"]').count(),4);
      assert.equal(await page.locator('.organize-count').textContent(),'4 处重点');
      await noOverflow(page,'.organize-board');
      await page.locator('.organize-board').screenshot({path:`${out}/${width}-focus-final.png`});
      await enter(page,'.radar-stage');
      const y = await page.evaluate(() => scrollY);
      await complete(page,'.opportunity-scene','radarPlayback');
      assert.equal(await page.evaluate(() => scrollY),y,'无需继续滚动，动效不移动页面');
      await noOverflow(page,'.opportunity-scene');
      assert.ok(await page.locator('.radar-stage').evaluate(e => e.querySelector('.radar-result').getBoundingClientRect().bottom <= e.getBoundingClientRect().bottom+1),'雷达结果不裁切');
      await page.locator('.opportunity-scene').screenshot({path:`${out}/${width}-reading-final.png`});
      await page.locator('.pitch-source-button').click();
      assert.ok(await page.locator('#pitch-evidence-dialog').evaluate(e => e.open));
      assert.equal(await page.locator('#pitch-evidence-dialog mark').count(),1);
      await noOverflow(page,'#pitch-evidence-dialog');
      await page.locator('#pitch-skip').click();
      assert.match(await page.locator('#pitch-answer-status').textContent(),/可以不补充/);
      await page.keyboard.press('Escape');
      assert.ok(await page.locator('.pitch-source-button').evaluate(e => e === document.activeElement));
      await enter(page,'.action-stage');
      await complete(page,'.action-scene','actionPlayback');
      assert.ok(await page.locator('.action-workspace').isHidden(),'不自动创建产物');
      await page.locator('.action-scene').screenshot({path:`${out}/${width}-choice-final.png`});
      await page.locator('#action-stop').click();
      assert.ok(await page.locator('.action-workspace').isHidden());
      await page.locator('#action-go').click();
      await page.waitForTimeout(550);
      assert.match(await page.locator('#action-editor').inputValue(),/校园调研/);
      await noOverflow(page,'.action-scene');
      await page.locator('.action-workspace').screenshot({path:`${out}/${width}-output-final.png`});
      assert.ok(await page.locator('.action-scene').evaluate(e => e.nextElementSibling.id === 'closing'));
      await page.close();
      console.log(`通过 ${width}×${height}：阅读重点、自动解读、原文/跳过、主动选择、编辑工作区与布局。`);
    }
    const page = await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce',acceptDownloads:true});
    watch(page);
    await page.goto(url);
    await complete(page,'.opportunity-scene','radarPlayback');
    await page.locator('.pitch-source-button').click();
    await page.locator('#pitch-answer').fill('合成补充：综测排名待学院确认');
    await page.locator('#pitch-confirm').click();
    assert.match(await page.locator('#pitch-note').inputValue(),/综测排名待学院确认/);
    const note = '  我的合成笔记：先核对本次认定。<b>仍为纯文本</b>  ';
    await page.locator('#pitch-note').fill(note);
    await page.locator('#pitch-keep').click();
    assert.match(await page.locator('#pitch-note-status').textContent(),/已保留当前版本/);
    await page.locator('#pitch-note').fill('尚未保留的新笔记');
    assert.match(await page.locator('#pitch-note-status').textContent(),/尚未保留新版/);
    await page.locator('.trust-close').focus();
    await page.keyboard.press('Shift+Tab');
    assert.ok(await page.locator('#pitch-discard').evaluate(e => e === document.activeElement));
    await page.keyboard.press('Escape');
    assert.equal(await page.locator('.action-note-preview p').textContent(),note.trim());
    assert.equal(await page.locator('.action-note-preview b').count(),0);
    await page.locator('#action-go').click();
    assert.match(await page.locator('#action-editor').inputValue(),/综测排名待学院确认/);
    assert.ok((await page.locator('#action-editor').inputValue()).includes(note.trim()));
    assert.ok(!(await page.locator('#action-editor').inputValue()).includes('尚未保留的新笔记'));
    const edited = ['本人编辑后的草稿', '保留本次修改。'].join(String.fromCharCode(10));
    await page.locator('#action-editor').fill(edited);
    await page.locator('[data-artifact="questions"]').click();
    assert.match(await page.locator('#action-editor').inputValue(),/待核实问题/);
    await page.locator('[data-artifact="draft"]').click();
    assert.equal(await page.locator('#action-editor').inputValue(),edited);
    const pendingDownload = page.waitForEvent('download');
    await page.locator('#action-download').click();
    const download = await pendingDownload;
    await download.saveAs(`${out}/download-verification.md`);
    const downloadedText = fs.readFileSync(`${out}/download-verification.md`,'utf8');
    assert.equal(downloadedText.startsWith(String.fromCharCode(0xFEFF)) ? downloadedText.slice(1) : downloadedText,edited);
    await page.locator('#action-stop').click();
    await page.locator('#action-go').click();
    assert.equal(await page.locator('#action-editor').inputValue(),edited);
    for (const key of ['research','business']) {
      await page.locator('#action-case').selectOption(key);
      assert.equal(await page.locator('.opportunity-scene').getAttribute('data-radar-case'),key);
      assert.ok(await page.locator('.action-workspace').isHidden());
      await page.locator('.pitch-source-button').click();
      assert.equal(await page.locator('#pitch-evidence-dialog').getAttribute('data-case'),key);
      assert.equal(await page.locator('#pitch-answer').inputValue(),'','场景间补充隔离');
      await page.keyboard.press('Escape');
      await page.locator('#action-go').click();
      assert.ok(!(await page.locator('#action-editor').inputValue()).includes('综测排名待学院确认'));
      assert.match(await page.locator('#action-editor').inputValue(),key === 'research' ? /申报核实问题/ : /合作讨论提纲/);
      await page.locator('[data-artifact="checklist"]').click();
      assert.match(await page.locator('#action-editor').inputValue(),/材料准备清单/);
    }
    await page.locator('button[data-radar-case="scholarship"]').click();
    assert.equal(await page.locator('#action-editor').inputValue(),edited);
    await page.locator('.pitch-source-button').click();
    assert.equal(await page.locator('#pitch-note').inputValue(),'尚未保留的新笔记');
    await page.locator('#pitch-discard').click();
    await page.keyboard.press('Escape');
    assert.ok(await page.locator('.action-note-preview').isHidden());
    await page.locator('[data-artifact="checklist"]').click();
    assert.ok(!(await page.locator('#action-editor').inputValue()).includes(note.trim()));
    await page.locator('button[data-radar-case="scholarship"]').focus();
    await page.keyboard.press('ArrowRight');
    assert.equal(await page.locator('.opportunity-scene').getAttribute('data-radar-case'),'research');
    await page.keyboard.press('End');
    assert.equal(await page.locator('.opportunity-scene').getAttribute('data-radar-case'),'business');
    await page.reload();
    assert.ok(await page.locator('.action-workspace').isHidden());
    assert.ok(await page.locator('.action-note-preview').isHidden());
    assert.ok(await page.locator('#action-replay').isHidden());
    await page.close();
    console.log('通过：三场景联动、补充、笔记版本/移除、纯文本、焦点、编辑保留、下载一致和刷新清除。');
    const motion = await browser.newPage({viewport:{width:1440,height:900}});
    watch(motion);
    await motion.goto(url);
    await enter(motion,'.action-stage');
    await motion.waitForFunction(() => +document.querySelector('.action-scene').dataset.actionProgress > .2);
    await motion.locator('.motion-toggle').click();
    const frozen = await progress(motion,'.action-scene','actionProgress');
    await motion.waitForTimeout(350);
    assert.equal(await progress(motion,'.action-scene','actionProgress'),frozen);
    await motion.locator('.motion-toggle').click();
    await motion.evaluate(() => scrollTo({top:0,behavior:'instant'}));
    await motion.waitForTimeout(100);
    const offscreen = await progress(motion,'.action-scene','actionProgress');
    await motion.waitForTimeout(350);
    assert.equal(await progress(motion,'.action-scene','actionProgress'),offscreen);
    await enter(motion,'.action-stage');
    await complete(motion,'.action-scene','actionPlayback');
    await motion.locator('.motion-toggle').click();
    await motion.locator('#action-go').click();
    assert.equal(await motion.locator('.action-workspace').evaluate(e => getComputedStyle(e).opacity),'1','暂停动效时主动打开的产物仍可见');
    await motion.locator('#action-case').selectOption('business');
    await motion.locator('.pitch-source-button').click();
    assert.equal(await motion.locator('#pitch-evidence-dialog').getAttribute('data-case'),'business','暂停时仍能主动切换场景、查看依据');
    await motion.locator('#pitch-answer').fill('A'.repeat(300));
    await motion.locator('#pitch-confirm').click();
    await motion.keyboard.press('Escape');
    await motion.locator('.pitch-source-button').click();
    await noOverflow(motion,'#pitch-evidence-dialog');
    await motion.keyboard.press('Escape');
    await motion.locator('.motion-toggle').click();
    await enter(motion,'.action-stage');
    await motion.locator('#action-replay').click();
    assert.ok(await progress(motion,'.action-scene','actionProgress') < .1);
    await motion.emulateMedia({reducedMotion:'reduce'});
    await complete(motion,'.action-scene','actionPlayback');
    assert.equal(await progress(motion,'.action-scene','actionProgress'),1);
    await motion.close();
    for (const width of [1440,320]) {
      const nojs = await browser.newPage({javaScriptEnabled:false,viewport:{width,height:900}});
      watch(nojs);
      await nojs.goto(url);
      assert.ok(await nojs.locator('#action-go').isDisabled());
      assert.ok(await nojs.locator('.action-workspace').isHidden());
      await noOverflow(nojs,'.opportunity-scene');
      assert.ok(await nojs.locator('.radar-stage').evaluate(e => e.querySelector('.radar-result').getBoundingClientRect().bottom <= e.getBoundingClientRect().bottom+1),'无 JS 结果不裁切');
      await nojs.locator('.trust-source-archive summary').click();
      assert.ok(await nojs.locator('.trust-source-archive').evaluate(e => e.open));
      await nojs.close();
    }
    const touch = await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true,reducedMotion:'reduce'});
    watch(touch);
    await touch.goto(url);
    await touch.locator('.pitch-source-button').tap();
    await touch.locator('#pitch-skip').tap();
    await touch.locator('.trust-close').tap();
    await touch.locator('#action-go').tap();
    await touch.locator('#action-editor').fill('触控编辑合成内容');
    assert.equal(await touch.locator('#action-editor').inputValue(),'触控编辑合成内容');
    await touch.close();
    assert.deepEqual(errors,[]);
    console.log('通过：暂停恢复、离屏冻结、重播、减少动态效果、无 JS 回退、触控、无页面错误或上传请求。');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
