/* 文件工作区浏览器验收：合成 HTTP 模型与 COS SDK 替身，非真实 LLM。 */
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const {chromium}=require('playwright');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1050},acceptDownloads:true});
 page.setDefaultTimeout(15000);
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const ready=()=>page.waitForFunction(()=>!document.body.classList.contains('busy'));
 const turns=async n=>{await page.locator('.assistant-message').nth(n-1).waitFor();await ready();};
 const send=async(msg,n)=>{await page.locator('#chat-input').fill(msg);await page.locator('#chat-send').click();await turns(n);};
 const close=async()=>{await page.locator('#finish').click();await page.locator('#welcome').waitFor({state:'visible'});};
 try{
  await page.goto('http://127.0.0.1:8790/');
  await page.evaluate(async()=>{const headers={'Content-Type':'application/json','X-FileAction-Token':document.querySelector('meta[name="fileaction-token"]').content};const status=await fetch('/api/status',{headers}).then(r=>r.json());if(!status.model.includes('合成HTTP测试替身'))throw new Error('仅允许清理隔离合成测试服务');const got=await fetch('/api/workspaces',{headers}).then(r=>r.json());for(const w of got.workspaces)await fetch('/api/workspace/delete',{method:'POST',headers,body:JSON.stringify({file_id:w.id,consent:true})});const memory=await fetch('/api/memory',{headers}).then(r=>r.json());for(const m of memory.entries)await fetch('/api/memory',{method:'POST',headers,body:JSON.stringify({action:'remove',target:m.target,entry_id:m.id,consent:true})});localStorage.clear();});
  await page.reload();
  await page.locator('#upload-consent').check();await page.locator('#persist-consent').check();await page.locator('#sample').click();
  await page.waitForFunction(()=>document.body.classList.contains('busy') && document.querySelector('.stream-text')?.textContent.length>3);
  assert.equal(await page.locator('.assistant-message').count(),0);await turns(1);
  console.log('PASS 模型完成前已显示流式文字，未用完整回复模拟打字');
  assert.match(await page.locator('#cos-file-state').textContent(),/COS.*已同步/);
  assert.match(await page.locator('#summary-highlights').textContent(),/截止|倒计时/);
  assert.equal(await page.locator('#summary-highlights a').getAttribute('href'),'https://example.com/synthetic-apply');
  await send('合成自述：我是老师，想给学生转发通知',2);
  assert.match(await page.locator('#file-knowledge').textContent(),/老师/);
  await fs.mkdir('/tmp/fileaction-workspace-browser',{recursive:true});await page.screenshot({path:'/tmp/fileaction-workspace-browser/desktop.png',fullPage:true});
  assert.equal(await page.locator('#memory-count').textContent(),'1');
  assert.equal(await page.locator('#file-knowledge').getByText('加入用户档案',{exact:true}).count(),0);
  assert.equal(await page.locator('.candidates').count(),0);
  await page.locator('.new-thread').click();await ready();
  assert.match(await page.locator('#profile-basis').textContent(),/老师/);
  await page.locator('#profile-basis .profile-edit').first().click();await page.locator('#memory-content').fill('合成修正：我是负责资助事务的行政人员');
  assert.equal(await page.locator('#memory-consent').count(),0);
  await page.locator('#memory-form button[type=submit]').click();await page.locator('#edit-memory-dialog').waitFor({state:'hidden'});
  await page.locator('#thread-tabs .thread-tab').first().click();await ready();
  assert.equal(await page.locator('.assistant-message').count(),2);
  assert.match(await page.locator('#context-note').textContent(),/更新|修改/);
  await send('按我的最新身份重新解释',3);
  const noOverlap=await page.evaluate(()=>document.querySelector('#chat-form').getBoundingClientRect().top>=document.querySelector('#agent-thread').getBoundingClientRect().bottom-1);assert.equal(noOverlap,true,'输入框不会覆盖对话正文');
  assert.match(await page.locator('.assistant-message').last().textContent(),/行政人员/);
  // 合成边界：下一次筛选结果改变，不应丢失已完成回复实际引用的档案快照。
  await page.route('**/api/workspace/open',async route=>{
    const response=await route.fetch();const doc=await response.json();doc.memory=[];
    await route.fulfill({response,json:doc});
  });
  await page.reload();await page.locator('#workspace').waitFor({state:'visible'});await ready();
  const analysisDownload=page.waitForEvent('download');await page.locator('#export-analysis').click();
  const exportedAnalysis=await analysisDownload;await exportedAnalysis.saveAs('/tmp/fileaction-analysis-snapshot.md');
  assert.match(await fs.readFile('/tmp/fileaction-analysis-snapshot.md','utf8'),/合成修正：我是负责资助事务的行政人员/);
  await page.unroute('**/api/workspace/open');await page.reload();await page.locator('#workspace').waitFor({state:'visible'});await ready();
  console.log('PASS 档案筛选改变后，解读导出仍保留本轮实际引用的依据');
  await page.locator('.new-thread').click();await ready();
  assert.equal(await page.locator('.assistant-message').count(),0);
  assert.match(await page.locator('#file-knowledge').textContent(),/行政人员/);
  await page.locator('#send-consent').check();await page.locator('#analyze').click();await turns(1);
  assert.match(await page.locator('.assistant-message').textContent(),/行政人员/);
  await page.locator('#thread-tabs .thread-tab').first().click();await ready();
  assert.equal(await page.locator('.assistant-message').count(),3);
  await page.locator('.action-choice').last().click();await page.locator('#action-confirm').check();await page.locator('#generate').click();
  await page.locator('#draft-section').waitFor({state:'visible'});await ready();
  await page.locator('#draft').fill('# 合成用户编辑\n工作区恢复验收');
  const downloading=page.waitForEvent('download');await page.locator('#export-draft').click();await downloading;
  await close();
  assert.equal(await page.locator('#recent-workspaces .workspace-card').count(),1);
  await page.locator('#recent-workspaces .workspace-open').click();await ready();
  assert.equal(await page.locator('.assistant-message').count(),3);
  assert.match(await page.locator('#draft').inputValue(),/工作区恢复验收/);
  await page.reload();await page.locator('#workspace').waitFor({state:'visible'});await ready();
  assert.equal(await page.locator('.assistant-message').count(),3);
  assert.equal(await page.locator('#thread-tabs .thread-tab').count(),3);
  console.log('PASS 自动沉淀、编辑优先、多会话隔离、关闭和刷新恢复、编辑导出（COS 替身）');
  await page.locator('.insight-details').first().locator('summary').click();await page.locator('.evidence').first().click();
  assert.equal(await page.locator('.source-line.highlight').count(),1);
  await page.locator('#chat-input').fill('无效引用合成测试');await page.locator('#chat-send').click();await ready();
  assert.match(await page.locator('#notice').textContent(),/引用校验失败/);
  assert.equal(await page.locator('.assistant-message').count(),3);
  await page.locator('#chat-input').fill('延迟合成测试');await page.locator('#chat-send').click();await page.locator('#cancel').click();await ready();
  await page.waitForTimeout(3300);assert.equal(await page.locator('.assistant-message').count(),3);
  await close();await page.locator('#persist-consent').uncheck();await page.locator('#upload-consent').check();
  await page.locator('#upload').setInputFiles({name:'合成采购.txt',mimeType:'text/plain',buffer:Buffer.from('合成采购事项\n采购需要核对数量和供应商交付日期。')});await turns(1);
  assert.match(await page.locator('.file-summary').textContent(),/采购/);
  assert.equal(await page.locator('#workspace-tabs .file-tab').count(),2);
  assert.match(await page.locator('#cos-file-state').textContent(),/临时/);
  for(const width of [1440,1024,768,390,320]){await page.setViewportSize({width,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`宽度${width}无溢出`);}
  await page.setViewportSize({width:390,height:844});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  await fs.mkdir('/tmp/fileaction-workspace-browser',{recursive:true});await page.screenshot({path:'/tmp/fileaction-workspace-browser/mobile.png',fullPage:true});
  await close();page.once('dialog',d=>d.accept());await page.locator('#recent-workspaces .workspace-delete').filter({hasText:'移除'}).first().click();await ready();
  await page.waitForFunction(()=>document.querySelectorAll('#recent-workspaces .workspace-card').length===1);
  await page.goto('http://127.0.0.1:8791/');await page.locator('#sample').click();await ready();await page.locator('#send-consent').check();await page.locator('#analyze').click();
  await page.locator('#settings-dialog').waitFor({state:'visible'});assert.equal(await page.locator('.assistant-message').count(),0);
  assert.deepEqual(errors,[]);
  console.log('PASS 原文引用、显式失败、取消迟到回复、多文件标签、移动布局、移除确认、未接入无假输出');
 }catch(e){console.error('界面状态：'+await page.locator('#notice').textContent());await page.screenshot({path:'/tmp/workspace-failure.png',fullPage:true});throw e;}finally{await browser.close();}
})().catch(e=>{console.error(e.stack);process.exit(1)});
