import { DEMO_DATE, SAMPLE_FILES } from './fixtures.mjs';

export function createViews({state,hasMemoryMode,esc,appButton,isBranchConfirmed,allMaterials,activeMaterials,elapsed}) {
  const icon = (name, className='') => {
    const paths={
      doc:'<path d="M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"/><path d="M14 3v6h6M8 13h8M8 17h6"/>',
      upload:'<path d="M12 16V3m-5 5 5-5 5 5M4 15v4a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-4"/>',
      arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',
      check:'<path d="m5 12 4 4L19 6"/>',
      close:'<path d="m6 6 12 12M6 18 18 6"/>',
      tools:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/>',
      memory:'<rect x="4" y="4" width="16" height="16" rx="4"/><path d="M8 9h8M8 13h8M8 17h4"/>',
      plus:'<path d="M12 5v14M5 12h14"/>',
      eye:'<path d="M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/>',
      back:'<path d="M19 12H5m6-6-6 6 6 6"/>'
    };
    return `<svg class="icon ${className}" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.doc}</svg>`;
  };
  const sourceText = doc => esc(doc.text.split('\n').map((line,i)=>`${String(i+1).padStart(2,'0')}  ${line}`).join('\n'));
  const statusColor = status => status==='可引用候选'?'teal':status==='不可用于本次'?'red':status==='需更新/确认'?'orange':status==='无法判断'?'blue':'';
  const stepIndex = () => ['notice','materials','results'].indexOf(state.tab);
  const closeButton = () => appButton(icon('close'),'close-dialog',{id:'close-dialog',className:'icon-button ghost',extra:'aria-label="关闭面板"'});
  const countScope = () => state.materials.length+state.pendingFiles.length;
  function sidebar() {
    return `<aside class="sidebar"><a href="index.html" class="brand"><span class="brand-symbol"><svg width="28" height="28" viewBox="0 0 28 28" fill="none" aria-hidden="true"><rect x="4" y="3" width="15" height="19" rx="4" fill="currentColor" opacity=".45"/><rect x="9" y="7" width="15" height="19" rx="4" fill="currentColor"/><path d="m13 17 2 2 5-5" stroke="#191d26" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg></span><span><span class="brand-name">DoAgent</span><span class="brand-en">让每次准备，接得上</span></span></a><div class="sidebar-section-title">当前演示</div><nav class="demo-switches" aria-label="演示场景"><a class="demo-switch ${hasMemoryMode?'active':''}" href="demo-with-memory.html" ${hasMemoryMode?'aria-current="page"':''}><span class="demo-letter">A</span><span>已有记忆<small>从上次的准备继续</small></span></a><a class="demo-switch ${!hasMemoryMode?'active':''}" href="demo-no-memory.html" ${!hasMemoryMode?'aria-current="page"':''}><span class="demo-letter">B</span><span>零记忆<small>一份通知就能开始</small></span></a></nav><section class="memory-side" aria-label="本机记忆摘要"><div class="memory-side-head">${icon('memory')}<span>本机记忆</span></div><div class="memory-count-big"><strong id="memory-count">${state.memory.length}</strong><span>份已保留资料</span></div>${state.memory.length?`<div class="memory-mini-list">${state.memory.slice(0,4).map(m=>`<div class="memory-mini-row ${m.active===false?'disabled':''}"><span>${esc(m.type)}</span><small>v${m.version}${m.active===false?' · 停用':''}</small></div>`).join('')}</div><p class="side-empty">每次仍按新通知重新核对</p>`:`<p class="side-empty">${hasMemoryMode?'载入合成记忆，体验下一次准备。':'这里是空的。先处理眼前这件事。'}</p>`}${hasMemoryMode&&!state.memory.length?appButton(icon('plus')+'载入 4 份演示记忆','seed-memory',{id:'load-memory',className:'side-button full'}):''}</section><div class="sidebar-bottom">${appButton(icon('tools')+'演示工具','open-tools',{id:'open-tools',className:'sidebar-tool'})}<a class="script-link" href="../03-参赛与路演/可行动事务Agent-Demo${hasMemoryMode?'一-已有记忆上传演示':'二-零记忆首次使用演示'}.md">查看演示脚本 ${icon('arrow')}</a><span class="sidebar-private">本机单人准备 · 未共享</span></div></aside>`;
  }
  function stepper() {
    return `<nav class="stepper" aria-label="准备流程">${[['notice','加入通知'],['materials','选择资料'],['results','准备清单']].map(([tab,label],i)=>`<button type="button" class="step-button ${state.tab===tab?'active':''} ${stepIndex()>i?'complete':''}" data-action="tab" data-tab="${tab}" ${state.tab===tab?'aria-current="step"':''} ${(i===1&&!state.notice)||(i===2&&!state.results&&!state.stale&&!state.busy)?'disabled':''}><span class="step-number">${stepIndex()>i?icon('check'):i+1}</span><span class="step-label">${label}</span></button>`).join('')}</nav>`;
  }
  function shell() {
    return `<div class="app-shell">${sidebar()}<main class="main"><header class="topbar"><span class="prototype-label"><span class="dot"></span>合成资料 · 规则模拟</span><div class="topbar-right">${appButton(icon('tools')+'记忆与工具','open-tools',{id:'mobile-tools',className:'ghost small mobile-tools'})}<a class="home-link" href="index.html">演示入口</a>${appButton(icon('plus')+'新事务','new-transaction',{id:'new-transaction',className:'ghost small'})}</div></header><div class="main-inner">${stepper()}${state.message&&(!state.stale||state.error)?`<div class="alert ${state.error?'error':''}" role="status" id="status-message"><span>${esc(state.error?state.message:state.message.split(/[；。]/)[0]+'。')}</span>${appButton(icon('close'),'dismiss',{className:'icon-button ghost',extra:'aria-label="关闭提示"'})}</div>`:''}${state.stale?`<div class="alert stale" role="alert" id="stale-banner"><span><strong>资料已变化，旧清单已过时。</strong> 重新检查后再审核、选用和导出。</span><span class="tag orange">v${state.version}</span></div>`:''}<div id="workspace" tabindex="-1">${state.tab==='notice'?noticeView():state.tab==='materials'?materialsView():resultsView()}</div><footer class="boundary">准备清单不代表整体资格通过，未对外提交。</footer></div></main></div>${dialogMarkup()}`;
  }
  function documentIllustration() {
    return `<div class="document-illustration" aria-hidden="true"><svg width="290" height="230" viewBox="0 0 290 230" fill="none"><circle cx="145" cy="115" r="104" fill="#eef1ff"/><rect x="72" y="37" width="144" height="172" rx="13" transform="rotate(-8 72 37)" fill="#d9e2ff"/><rect x="91" y="22" width="144" height="172" rx="13" transform="rotate(6 91 22)" fill="white" stroke="#e0e5ef"/><rect x="108" y="55" width="34" height="9" rx="4.5" transform="rotate(6 108 55)" fill="#315bf4"/><path d="m108 91 88 9m-91 17 71 7m-74 20 81 8" stroke="#d8deeb" stroke-width="6" stroke-linecap="round"/><circle cx="222" cy="173" r="27" fill="#315bf4"/><path d="m210 173 8 8 16-17" stroke="white" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><circle cx="52" cy="112" r="5" fill="#b6c8ff"/><circle cx="247" cy="67" r="4" fill="#b6c8ff"/></svg></div>`;
  }
  function fileZone(kind,compact=false) {
    const notice=kind==='notice';
    return `<div class="dropzone ${compact?'compact':''}" data-drop-kind="${kind}"><div class="upload-icon">${icon('upload')}</div><div class="upload-copy"><h3>${notice?'拖入一份通知，开始准备':'把本次需要的资料拖到这里'}</h3><p>${notice?'约定格式 TXT · 每份不超过 100 KB':'约定格式 TXT · 每份不超过 100 KB · 最多 5 份'}</p></div><div class="upload-actions"><label class="button ${notice?'primary':'soft'}" for="${kind}-file">${icon('plus')}${notice?'选择通知文件':'选择资料文件'}</label><input class="sr-only" type="file" id="${kind}-file" data-testid="${kind}-file" data-file-kind="${kind}" accept=".txt,text/plain" ${notice?'':'multiple'}></div></div>`;
  }
  function sampleNoticeRow() {
    return `<div class="sample-notice"><span class="sample-icon">${icon('doc')}</span><div class="sample-copy"><strong>星桥学生项目实践计划 · 第二期</strong><span>试用通知样例，看看它需要哪些材料</span></div>${appButton('使用样例 '+icon('arrow'),'load-notice',{id:'load-notice',className:'ghost'})}</div>`;
  }
  function noticeView() {
    const n=state.notice;
    if(!n)return `<section class="step-view notice-empty"><div class="welcome-grid"><div class="welcome-copy"><div class="eyebrow">${hasMemoryMode?'从上次的准备继续':'不必先建立个人档案'}</div><h1>${hasMemoryMode?'新通知来了，<br>准备不用从头开始。':'一份通知，<br>就是准备的起点。'}</h1><p>${hasMemoryMode?'带上已有资料，看清哪些能复用、哪些需要更新。':'先看清需要什么，再决定补充哪些资料。'}</p></div>${documentIllustration()}</div><section class="upload-card">${fileZone('notice')}${sampleNoticeRow()}</section>${pasteControl('notice')}<p class="quiet-note">先得到要求清单；资料和记忆都可以稍后加入。</p></section>`;
    return `<section class="step-view"><div class="workspace-head"><div><div class="eyebrow">第一步 · 加入通知</div><h1>这次，需要准备什么？</h1><p>已整理出 ${n.requirements.length} 项要求。先核对关键条件，再选资料。</p></div><span class="tag teal">通知已读取</span></div><div class="notice-layout"><section class="panel notice-panel"><div class="notice-header"><span class="file-icon">${icon('doc')}</span><div><h2>${esc(n.title)}</h2><p>${esc(n.filename)} · ${esc(n.id)} v${n.version}</p></div>${appButton(icon('eye'),'open-notice',{id:'view-notice',className:'icon-button ghost',extra:'aria-label="查看通知原文"'})}</div><div class="requirement-list">${n.requirements.map((r,i)=>`<div class="requirement-row"><span class="requirement-number">${String(i+1).padStart(2,'0')}</span><div><strong>${esc(r.title)}</strong><p>${esc(r.quote)}</p></div></div>`).join('')}</div><div class="notice-panel-footer"><label class="button ghost small" for="notice-file">更换通知</label><input class="sr-only" type="file" id="notice-file" data-testid="notice-file" data-file-kind="notice" accept=".txt,text/plain">${appButton('查看原文与行号','open-notice',{className:'ghost small'})}</div></section>${confirmationPanel()}</div><div class="actionbar"><div class="actionbar-copy">资料可以跳过，未确认的条件会保留待核实。</div><div class="button-row">${appButton('先生成要求清单','run',{id:'run-check',className:'ghost',disabled:state.busy||state.uploading})}${appButton('下一步：选择资料 '+icon('arrow'),'tab',{id:'go-materials',className:'primary',extra:'data-tab="materials"'})}</div></div></section>`;
  }
  function confirmationPanel() {
    const n=state.notice,three=state.deadlineConfirmed&&state.channelConfirmed&&state.prohibitionConfirmed;
    return `<aside class="panel confirmation-panel" id="confirmation-panel"><div class="panel-heading"><h2>一次核对关键条件</h2><span class="tag ${isBranchConfirmed()?'teal':''}">${isBranchConfirmed()?'已确认':'待确认'}</span></div><label class="field" for="identity-branch">本次适用身份<select id="identity-branch" data-testid="identity-branch"><option value="" ${state.branch===''?'selected':''}>选择身份分支</option><option value="applicable" ${state.branch==='applicable'?'selected':''}>${esc(n.branch)}</option><option value="uncertain" ${state.branch==='uncertain'?'selected':''}>不确定，保留待核实</option></select></label><div class="confirm-fact"><label><input type="checkbox" id="confirm-deadline" data-confirm="deadlineConfirmed" ${state.deadlineConfirmed?'checked':''}><span><small>截止日期</small><strong>${esc(n.deadline)}</strong></span></label></div><div class="confirm-fact"><label><input type="checkbox" id="confirm-channel" data-confirm="channelConfirmed" ${state.channelConfirmed?'checked':''}><span><small>提交渠道</small><strong>${esc(n.channel)}</strong></span></label></div><div class="confirm-fact"><label><input type="checkbox" id="confirm-prohibition" data-confirm="prohibitionConfirmed" ${state.prohibitionConfirmed?'checked':''}><span><small>禁用条件</small><strong>${esc(n.requirements.find(r=>r.id==='R4')?.quote||'以通知原文为准')}</strong></span></label></div>${appButton(three?icon('check')+'三项已核对':'一次确认以上三项','confirm-all',{id:'confirm-all',className:three?'soft full':'full',disabled:three})}<p class="plain-note">附件 A 未提供，特殊身份要求将保留待核实。</p></aside>`;
  }
  function pasteControl(kind) {
    return `<details data-open-key="paste-${kind}" class="detail-block paste-control" ${state.pasteOpen&&state.pasteKind===kind?'open':''}><summary>读取有困难？粘贴 TXT 文本</summary><div class="paste-panel">${kind==='material'&&state.pendingFiles.length?`<label class="field" for="paste-replacement">替代哪份未读取的资料<select id="paste-replacement"><option value="">只追加，不替代未读取项</option>${state.pendingFiles.map(p=>`<option value="${esc(p.filename)}">替代：${esc(p.filename)}</option>`).join('')}</select></label>`:''}<label class="field" for="paste-text-${kind}">仍使用相同的格式校验<textarea id="paste-text-${kind}" placeholder="资料格式：行动事务演示TXT-v1&#10;类型：${kind==='notice'?'通知':'材料'}&#10;……">${esc(state.pasteText[kind])}</textarea></label>${appButton('读取粘贴文本','parse-paste',{id:`parse-paste-${kind}`,className:'soft',extra:`data-kind="${kind}"`})}</div></details>`;
  }
  function materialRow(m) {
    const inUse=state.materials.some(d=>d.id===m.id),saved=state.memory.some(d=>d.id===m.id&&d.version===m.version&&d.text===m.text);
    return `<article class="material-row ${m.active===false?'disabled':''}" data-material-id="${esc(m.id)}"><label class="material-check"><input type="checkbox" id="use-${esc(m.id)}" data-use-material="${esc(m.id)}" ${inUse?'checked':''} ${m.active===false&&!inUse?'disabled':''}><span class="sr-only">本次使用 ${esc(m.title)}</span></label><span class="file-icon">${icon('doc')}</span><div class="material-copy"><h3>${esc(m.title)}</h3><p>${esc(m.id)} · v${m.version} · ${esc(m.role||m.type)} <span>· ${m.active===false?'已停用':saved?'已保留资料':'仅本次使用'}</span></p></div><div class="material-row-actions"><span class="tag ${m.active===false?'':saved?'blue':''}">${m.active===false?'已停用':inUse?'本次使用':'未选择'}</span>${appButton('查看详情','open-material',{id:`view-${esc(m.id)}`,className:'ghost small',extra:`data-id="${esc(m.id)}"`})}</div></article>`;
  }
  function materialsView() {
    const docs=allMaterials();
    return `<section class="step-view"><div class="workspace-head"><div><div class="eyebrow">第二步 · 选择资料</div><h1>${hasMemoryMode&&state.memory.length?'已有资料，可以接着用。':'选本次需要的几份资料。'}</h1><p>${hasMemoryMode&&state.memory.length?'已带入保存的来源。旧资料是否适用，下一步按新通知核对。':'资料只用于本次准备，稍后再决定是否保留。'}</p></div><span class="tag blue" id="selected-material-count">本次 ${countScope()} / 5 份</span></div><section class="panel material-panel"><div class="materials-toolbar"><h2>${hasMemoryMode&&state.memory.length?'可复用与新加入的资料':'本次资料'}</h2><span>${activeMaterials().length} 份参与检查</span></div><div class="materials-list">${docs.length?docs.map(materialRow).join(''):`<div class="materials-empty"><span class="file-icon">${icon('doc')}</span><div><h3>还没有个人资料</h3><p>可以直接生成要求清单，材料状态会保留“未检查”。</p></div></div>`}</div>${state.pendingFiles.length?`<div class="pending-files">${state.pendingFiles.map(p=>`<div class="pending-row"><div><strong>${esc(p.filename)}</strong><span>读取失败 · 这份资料仍未检查</span></div>${appButton('移除','remove-pending',{className:'ghost small',extra:`data-filename="${esc(p.filename)}"`})}</div>`).join('')}</div>`:''}${fileZone('material',true)}</section><div class="materials-extras"><details class="samples-drawer" data-open-key="material-samples"><summary>使用合成资料演示</summary><div class="sample-actions">${appButton('载入 4 份合成资料','load-material-samples',{id:'load-material-samples',className:'soft small'})}<label class="field" for="sample-choice">或选择一份<select id="sample-choice">${SAMPLE_FILES.filter(f=>f.kind==='material').map(f=>`<option value="${esc(f.filename)}" ${state.selectedSample===f.filename?'selected':''}>${esc(f.label)}</option>`).join('')}</select></label>${appButton('载入所选样例','load-selected-sample',{id:'load-selected-sample',className:'small'})}${appButton('下载所选 TXT','download-selected-sample',{id:'download-material',className:'ghost small'})}</div></details>${appButton(icon('plus')+'加入第二期新名单','load-new-roster',{id:'load-new-roster',className:'ghost small',disabled:state.materials.some(m=>m.id==='P05')})}</div>${pasteControl('material')}<div class="actionbar"><div class="actionbar-copy">${appButton(icon('back')+'上一步','tab',{className:'ghost small',extra:'data-tab="notice"'})}</div><div class="button-row">${countScope()?appButton('跳过资料','skip-materials',{id:'skip-materials',className:'ghost'}):''}${appButton((countScope()?'生成准备清单':'先生成要求清单')+' '+icon('arrow'),'run',{id:'run-check',className:'primary',disabled:!state.notice||state.busy||state.uploading})}</div></div></section>`;
  }
  function resultRow(r) {
    const reviewed=state.reviewed.has(r.id),selected=state.selected.has(r.id);
    return `<article class="result-row ${selected?'selected':''}" id="result-${esc(r.id)}" data-testid="result-${esc(r.id)}"><div class="result-title"><span class="requirement-number">${esc(r.id.replace('R','').padStart(2,'0'))}</span><strong>${esc(r.title)}</strong></div><div class="result-material">${r.materialIds.length?r.materialIds.map(id=>`${esc(id)} <small>v${r.materialVersions[id]}</small>`).join('、'):'<span class="muted">暂无个人依据</span>'}</div><div class="result-state"><span class="tag ${statusColor(r.status)}" data-testid="status-${esc(r.id)}">${esc(r.status)}</span><span class="result-review ${selected?'is-selected':''}">${selected?'已审核 · 已选用':reviewed?'已核对依据':r.status==='可引用候选'?'待你审核':''}</span></div>${appButton('查看依据 '+icon('arrow'),'open-result',{id:`view-result-${esc(r.id)}`,className:'ghost small',extra:`data-id="${esc(r.id)}"`})}</article>`;
  }
  function loadingView() {
    const stages=['读取本次要求','配对所选资料','整理准备清单'];
    return `<section class="loading-surface" aria-live="polite"><div class="loading-orbit">${icon('doc')}</div><h2>把要求和资料对齐</h2><p>正在执行本地规则检查</p><div class="analysis-stages">${stages.map((label,i)=>`<div class="analysis-stage ${state.analysisStage===i?'active':''} ${state.analysisStage>i?'complete':''}"><span>${state.analysisStage>i?icon('check'):i+1}</span>${label}</div>`).join('')}</div><div class="loading-skeleton"><i></i><i></i><i></i></div></section>`;
  }
  function resultsView() {
    const results=state.results;
    if(state.busy)return `<section class="step-view"><div class="workspace-head"><div class="eyebrow">第三步 · 准备清单</div></div>${loadingView()}</section>`;
    if(!results)return `<section class="step-view"><div class="workspace-head"><div><div class="eyebrow">第三步 · 准备清单</div><h1>${state.stale?'资料变了，重新对齐一下。':'你的下一步，会在这里。'}</h1><p>${state.stale?'旧审核与选用已清除，重新检查后再导出。':'加入通知，即可得到要求清单。'}</p></div></div><section class="empty-surface">${icon('doc')}<h2>${state.stale?'重新检查当前版本':'还未生成清单'}</h2>${appButton('重新生成准备清单','run',{id:'run-check',className:'primary',disabled:!state.notice||state.uploading})}</section><div class="actionbar">${appButton(icon('back')+'返回选择资料','tab',{className:'ghost',extra:'data-tab="materials"'})}${state.stale?appButton('重新检查后可导出','export',{id:'export-draft',className:'small',disabled:true}):''}</div></section>`;
    return `<section class="step-view"><div class="workspace-head"><div><div class="eyebrow">第三步 · 准备清单</div><h1>${activeMaterials().length?'准备的下一步，清楚了。':'先有清单，资料慢慢补齐。'}</h1><p>${esc(state.notice.title)}<span class="result-snapshot"> · v${state.version}</span></p></div>${appButton('重新检查','run',{id:'run-check',className:'ghost small',disabled:state.busy})}</div><div class="result-summary"><div class="summary-stat"><strong>${results.filter(r=>r.status==='可引用候选').length}</strong><span>可引用候选</span><small>仍需本次审核</small></div><div class="summary-stat"><strong>${results.filter(r=>r.status!=='可引用候选'&&r.status!=='不可用于本次').length}</strong><span>待补充或核实</span></div><div class="summary-stat"><strong>${results.filter(r=>r.status==='不可用于本次').length}</strong><span>本次排除</span></div><div class="summary-context"><span>${activeMaterials().length} 份资料 · ${state.pendingFiles.length} 份读取缺口</span><span>${isBranchConfirmed()?'关键条件已确认':'关键条件待确认'}</span></div></div><section class="panel result-table" aria-label="材料准备清单"><div class="result-table-head"><span>材料要求</span><span>资料依据</span><span>本次状态</span><span>核对</span></div><div id="result-list">${results.map(resultRow).join('')}</div></section><div class="result-footnote"><span>${state.selected.size} 项已审核并选用</span><span>未检查和待核实项也会随清单导出</span></div><div class="actionbar"><div class="actionbar-copy">${appButton(icon('back')+'调整资料','tab',{className:'ghost small',extra:'data-tab="materials"'})}</div><div class="button-row">${appButton('为下次保留','open-save',{id:'open-save',className:'ghost'})}${appButton(icon('upload')+'导出准备清单','export',{id:'export-draft',className:'primary',disabled:state.stale||state.busy})}</div></div></section>`;
  }
  function evidenceMarkup(e,label) {
    if(!e)return '';
    return `<div class="rule-source"><div class="source-heading"><strong>${label}</strong><span>${esc(e.sourceId)} v${e.version}</span></div><p>${esc(e.filename)} · 第 ${e.lineStart}–${e.lineEnd} 行</p><pre>${esc(e.text)}</pre></div>`;
  }
  function resultDetail(r) {
    const candidate=r.status==='可引用候选',reviewed=state.reviewed.has(r.id),selected=state.selected.has(r.id);
    return `<div class="dialog-header"><div><span class="eyebrow">${esc(r.id)} · 本次判断依据</span><h2 id="dialog-title">${esc(r.title)}</h2></div>${closeButton()}</div><div class="dialog-body"><div class="detail-verdict"><span class="tag ${statusColor(r.status)}">${esc(r.status)}</span><p>${esc(r.reason)}</p><div class="result-next"><strong>下一步</strong><span>${esc(r.nextStep)}</span></div></div><div class="source-chain">${evidenceMarkup(r.ruleEvidence,'本次通知要求')}${r.evidence.map(e=>evidenceMarkup(e,'个人资料依据')).join('')}${r.pairs.filter(p=>!r.materialIds.includes(p.materialId)||p.status!==r.status).map(p=>`<div class="rule-source excluded-source"><div class="source-heading"><strong>同时检查的旧资料</strong><span>${esc(p.materialId)} v${p.materialVersion}</span></div><span class="tag ${statusColor(p.status)}">${esc(p.status)}</span><p>${esc(p.reason)}</p>${p.evidence.map(e=>`<pre>${esc(e.filename)} · 第 ${e.lineStart}–${e.lineEnd} 行\n${esc(e.text)}</pre>`).join('')}</div>`).join('')}</div><p class="coverage-note">${esc(r.coverage.description)} · 当前事务 v${state.version}</p></div><div class="dialog-footer review-controls"><label class="check-row"><input type="checkbox" id="review-${esc(r.id)}" data-testid="review-${esc(r.id)}" data-review="${esc(r.id)}" ${reviewed?'checked':''} ${!r.evidence.length?'disabled':''}><span>我已核对本次依据</span></label><label class="check-row"><input type="checkbox" id="select-${esc(r.id)}" data-testid="select-${esc(r.id)}" data-select-result="${esc(r.id)}" ${selected?'checked':''} ${!candidate||!reviewed?'disabled':''}><span>${r.status==='不可用于本次'?'本次禁止选用':'选用于准备清单'}</span></label></div>`;
  }
  function materialDetail(m) {
    const saved=state.memory.some(d=>d.id===m.id&&d.version===m.version&&d.text===m.text);
    return `<div class="dialog-header"><div><span class="eyebrow">${esc(m.id)} · 资料来源</span><h2 id="dialog-title">${esc(m.title)}</h2></div>${closeButton()}</div><div class="dialog-body"><div class="material-detail-meta"><span class="tag ${saved?'blue':''}">${saved?'已保留资料':'仅本次使用'}</span><span>v${m.version} · ${esc(m.owner||'来源未注明')}</span></div><dl class="detail-facts"><div><dt>历史确认</dt><dd>${esc(m.memoryConfirmedAt||m.confirmedAt||'未提供')}</dd></div><div><dt>适用范围</dt><dd>${esc(m.fields?.['适用范围']||'仅供本次材料检查')}</dd></div><div><dt>可见范围</dt><dd>本机本人</dd></div>${m.role?`<div><dt>项目角色</dt><dd>${esc(m.role)}</dd></div>`:''}</dl><h3>来源原文与行号</h3><pre class="source-text">${sourceText(m)}</pre>${m.corrections?.length?'<p class="plain-note">纠正补充已写入新版本，历史事实保留在来源中。</p>':''}</div><div class="dialog-footer material-footer"><div class="button-row">${appButton(m.active===false?'启用资料':'停用资料','toggle-material',{id:`toggle-${m.id}`,className:'ghost small',extra:`data-id="${esc(m.id)}"`})}${appButton('删除资料','delete-material',{id:`delete-${m.id}`,className:'ghost small danger-text',extra:`data-id="${esc(m.id)}"`})}</div>${m.id==='P02'?appButton(m.role==='项目成员'?'已更正为项目成员':'更正为项目成员','correct-role',{id:`correct-${m.id}`,className:'soft small',disabled:m.role==='项目成员',extra:`data-id="${esc(m.id)}"`}):''}</div>`;
  }
  function saveDetail() {
    const docs=activeMaterials();
    return `<div class="dialog-header"><div><span class="eyebrow">可选 · 为下次保留</span><h2 id="dialog-title">下次，从这里接着准备。</h2></div>${closeButton()}</div><div class="dialog-body"><p class="dialog-intro">只保留你核对并选择的来源文本、版本与确认事实。下一次仍按新通知重新审核。</p>${docs.length?`<div class="save-options">${docs.map(m=>`<div class="save-row"><div class="save-title"><span class="file-icon">${icon('doc')}</span><div><strong>${esc(m.type)}</strong><span>${esc(m.id)} · v${m.version}</span></div></div><div class="save-checks"><label class="check-row"><input type="checkbox" data-save-reviewed="${esc(m.id)}" id="save-reviewed-${esc(m.id)}" ${state.saveChecked.has(m.id)?'checked':''}>已核对这份资料</label><label class="check-row"><input type="checkbox" data-save-candidate="${esc(m.id)}" id="save-${esc(m.id)}" ${state.saveCandidates.has(m.id)?'checked':''} ${!state.saveChecked.has(m.id)?'disabled':''}>保留到本机记忆</label></div></div>`).join('')}</div>`:'<div class="materials-empty"><p>本次没有个人资料需要保留，可以直接结束。</p></div>'}${state.saveMessage?`<p class="save-status" role="status">${esc(state.saveMessage)}</p>`:''}</div><div class="dialog-footer"><div class="button-row">${appButton('不保存，结束本次','finish-without-save',{id:'finish-without-save',className:'ghost'})}</div>${state.ended||state.saveMessage?appButton('开始新事务 '+icon('arrow'),'new-transaction',{className:'primary'}):appButton('保留所选资料','save-memory',{id:'save-memory',className:'primary',disabled:!state.saveCandidates.size||state.stale||!state.results})}</div>`;
  }
  function toolsDetail() {
    const risks=[['首次没有记忆','先上传通知就能获得要求清单；跳过资料时六项均保留“未检查”，不强迫建档。'],['找文件和确认成本','只选择本次相关资料，最多 5 份；集中核对身份、期限、渠道与禁用条件。寻找和辅助时间单独记录。'],['文件存在，但本次不适用','旧名单标记需更新，往期已申报成果排除；每项结果可查看通知规则、原文行号及旧资料限制。'],['记忆过期或纠正失效','资料详情可纠正、停用、删除。旧结果与审核立即失效；重新检查后才能导出。保存后由新事务实际重读。'],['支持与调用失控','相同版本使用缓存；技术失败最多重试一次，语义不明保留待核实。失败文件保留覆盖缺口，不当作已检查。'],['协作与企业扩张','本次仅演示负责人个人准备：本机存储、未共享、未分派、未提交。团队与企业需求另行验证。']];
    return `<div class="dialog-header"><div><span class="eyebrow">给演示者</span><h2 id="dialog-title">演示工具</h2></div>${closeButton()}</div><div class="dialog-body"><section class="tool-section"><h3>运行与成本</h3><div class="metrics"><div class="metric"><span>本次实际耗时</span><strong id="elapsed-time">${elapsed()}</strong></div><div class="metric"><span>模拟分析</span><strong id="analysis-count">${state.stats.analyses}</strong></div><div class="metric"><span>版本缓存命中</span><strong id="cache-hit-count">${state.stats.cacheHits}</strong></div><div class="metric"><span>技术重试</span><strong id="retry-count">${state.stats.retries}</strong></div><div class="metric"><span>真实模型调用</span><strong>0</strong></div></div><div class="cost-inputs"><label class="field" for="find-minutes">找文件时间（分钟）<input type="number" min="0" step="0.5" id="find-minutes" value="${state.findMinutes}"></label><label class="field" for="help-minutes">他人辅助时间（分钟）<input type="number" min="0" step="0.5" id="help-minutes" value="${state.helpMinutes}"></label></div><p class="plain-note">演示规则日期 ${DEMO_DATE}。计时重叠项不直接相加；这里不是已经验证的节时结论。</p></section><section class="tool-section"><h3>故障演练</h3><label class="field" for="failure-mode">模拟技术失败（绕过缓存）<select id="failure-mode" data-testid="failure-mode"><option value="off" ${state.failMode==='off'?'selected':''}>关闭 · 正常检查</option><option value="once" ${state.failMode==='once'?'selected':''}>首次失败 · 重试一次后成功</option><option value="always" ${state.failMode==='always'?'selected':''}>持续失败 · 重试一次后停止</option></select></label><p class="plain-note">关闭面板后，点击“重新检查”运行。规则歧义不重试；过时返回已丢弃 ${state.stats.dropped} 次。</p></section><section class="tool-section"><h3>六个问题，在页面中怎样处理</h3><div class="risk-list">${risks.map(([title,body],i)=>`<div class="risk-item"><span class="requirement-number">0${i+1}</span><div><strong>${title}</strong><p>${body}</p></div></div>`).join('')}</div></section><section class="tool-section"><h3>素材与本机数据</h3><div class="sample-downloads">${SAMPLE_FILES.map(f=>appButton(icon('doc')+esc(f.filename),'download-sample',{className:'ghost small',extra:`data-filename="${esc(f.filename)}"`})).join('')}</div><div class="button-row">${hasMemoryMode?appButton('载入演示记忆','seed-memory',{id:'seed-memory-tools',className:'soft small'}):''}${appButton('重新读取本机记忆','reload-memory',{id:'reload-memory',className:'small'})}${appButton('清空本演示数据','reset',{id:'reset-demo',className:'ghost small danger-text'})}</div><p class="plain-note">真实读取约定格式 TXT、保存到浏览器并下载 Markdown；规则判断为本地模拟。未接入 AI，不支持 PDF 或 OCR。A、B 的本机空间独立。</p></section></div><div class="dialog-footer">${appButton('返回演示','close-dialog',{className:'primary'})}</div>`;
  }
  function dialogMarkup() {
    if(!state.dialog)return '';
    let content='',kind=state.dialog;
    if(kind==='result') { const r=state.results?.find(r=>r.id===state.activeResult);if(!r)return '';content=resultDetail(r); }
    else if(kind==='material') { const m=allMaterials().find(m=>m.id===state.activeMaterial);if(!m)return '';content=materialDetail(m); }
    else if(kind==='save')content=saveDetail();
    else if(kind==='tools')content=toolsDetail();
    else if(kind==='notice'&&state.notice)content=`<div class="dialog-header"><div><span class="eyebrow">${esc(state.notice.id)} · v${state.notice.version}</span><h2 id="dialog-title">通知原文</h2></div>${closeButton()}</div><div class="dialog-body"><pre class="source-text">${sourceText(state.notice)}</pre>${pasteControl('notice')}</div><div class="dialog-footer">${appButton('返回核对','close-dialog',{className:'primary'})}</div>`;
    if(!content)return '';
    if(state.error&&state.message)content=content.replace('<div class="dialog-body">',`<div class="dialog-body"><div class="alert error" role="alert">${esc(state.message)}</div>`);
    return `<dialog id="app-dialog" class="app-dialog ${kind}-dialog" aria-labelledby="dialog-title">${content}</dialog>`;
  }
  return {shell};
}
