// 从仓库根目录运行，PLAYWRIGHT_MODULE 可指定本机 Playwright 路径。
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert = require('node:assert/strict');
const output = '.planning/2026-10-02-interactive-scenes';
const url = 'http://127.0.0.1:8787/07-宣传页/';

(async () => {
  const browser = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true });
  try {
    const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(url);
    await page.waitForTimeout(1700);
    async function mouseClick(locator) {
      const rect = await locator.boundingBox();
      assert.ok(rect && rect.width, '点击对象可见');
      await page.mouse.click(rect.x + rect.width / 2, rect.y + rect.height / 2);
    }
    const positions = () => page.locator('.file-slot').evaluateAll(slots => slots.filter(slot => slot.offsetWidth).map(slot => slot.getBoundingClientRect().x));
    const initial = await positions();
    await page.locator('.deck-toggle').click();
    await page.waitForTimeout(1100);
    const gathered = await positions();
    assert.ok(Math.max(...gathered) - Math.min(...gathered) < 60, '文件聚拢到中心');
    assert.equal(await page.locator('.deck-toggle').getAttribute('aria-pressed'), 'true');
    await page.screenshot({ path: `${output}/deck.png` });
    await page.locator('.deck-toggle').click();
    await page.waitForTimeout(1100);
    const expanded = await positions();
    assert.ok(Math.max(...expanded) - Math.min(...expanded) > 900, '文件重新展开');
    assert.ok(Math.abs(initial[3] - expanded[3]) < 10);
    const featured = page.locator('.file-slot-featured .file-open');
    await mouseClick(featured);
    await page.waitForFunction(() => document.querySelector('.file-preview').open);
    assert.ok(await page.locator('.file-preview').evaluate(el => el.getAnimations().length > 0), '预览从源卡片动画展开');
    await page.waitForTimeout(650);
    assert.match(await page.locator('#file-preview-title').innerText(), /好想法/);
    await page.screenshot({ path: `${output}/preview.png` });
    await page.keyboard.press('ArrowRight');
    assert.equal(await page.locator('#file-preview-title').innerText(), '实习简章');
    await page.locator('.preview-explore').click();
    await page.waitForFunction(() => !document.querySelector('.file-preview').open);
    assert.equal(await page.locator('#tab-internship').getAttribute('aria-selected'), 'true');
    assert.equal(await page.evaluate(() => document.body.classList.contains('modal-open')), false);
    await page.waitForTimeout(900);
    await page.locator('#tab-scholarship').click();
    await page.waitForTimeout(500);
    assert.ok(await page.evaluate(() => {
      const tab = document.querySelector('#tab-scholarship').getBoundingClientRect();
      const glider = document.querySelector('.tab-glider').getBoundingClientRect();
      return Math.abs(tab.x - glider.x) < 2 && Math.abs(tab.width - glider.width) < 2;
    }), '场景滑块对齐当前选择');
    await page.locator('#view-source').click();
    await page.keyboard.press('Escape');
    const download = page.waitForEvent('download');
    await page.locator('#export-checklist').click();
    assert.match((await download).suggestedFilename(), /奖学金/);
    await page.locator('.constellation').scrollIntoViewIfNeeded();
    await page.waitForTimeout(900);
    assert.equal(await page.locator('.graph-path').count(), 8);
    const node = page.locator('[data-node="project"]');
    const baseline = await node.evaluate(el => ({ left: el.style.left, top: el.style.top }));
    const initialPath = await page.locator('.graph-path').first().getAttribute('d');
    await node.click();
    assert.equal(await node.getAttribute('aria-pressed'), 'true');
    assert.match(await page.locator('#graph-title').innerText(), /已有材料/);
    assert.equal(await page.locator('.graph-path.is-active').count(), 2);
    const box = await node.boundingBox();
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
    await page.mouse.down();
    await page.mouse.move(box.x + box.width / 2 + 35, box.y + box.height / 2 + 32, { steps: 8 });
    assert.equal(await node.evaluate(el => el.classList.contains('is-dragging')), true);
    await page.mouse.up();
    assert.notEqual(await page.locator('.graph-path').first().getAttribute('d'), initialPath, '曲线跟随真实鼠标拖动');
    const dragged = await node.evaluate(el => parseFloat(el.style.left));
    await node.focus();
    await node.press('ArrowRight');
    assert.ok(await node.evaluate(el => parseFloat(el.style.left)) > dragged, '键盘可移动节点');
    await page.locator('.constellation-hub').click();
    assert.equal(await page.locator('.graph-path.is-active').count(), 8);
    await page.screenshot({ path: `${output}/graph.png` });
    await page.locator('.graph-reset').click();
    await page.waitForTimeout(200);
    const resetMidPath = await page.locator('.graph-path').first().getAttribute('d');
    await page.waitForTimeout(550);
    assert.deepEqual(await node.evaluate(el => ({ left: el.style.left, top: el.style.top })), baseline, '重置归位');
    assert.equal(await page.locator('.graph-path').first().getAttribute('d'), initialPath, '重置恢复初始曲线');
    assert.notEqual(resetMidPath, initialPath, '归位过程中连线随节点插值');
    assert.equal(await page.locator('.graph-path.is-active').count(), 0);
    // 拖出区域仍可正常释放，下次可以继续操作。
    const box2 = await node.boundingBox();
    await page.mouse.move(box2.x + 20, box2.y + 20);
    await page.mouse.down();
    await page.mouse.move(10, 20, { steps: 5 });
    await page.mouse.up();
    assert.equal(await node.evaluate(el => el.classList.contains('is-dragging')), false);
    assert.ok(await node.evaluate(el => {
      const nodeRect = el.getBoundingClientRect(), stage = el.parentElement.getBoundingClientRect();
      return nodeRect.left >= stage.left && nodeRect.top >= stage.top;
    }), '拖动限制在星图内');
    await page.locator('.graph-reset').click();
    await page.waitForTimeout(700);
    await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
    await page.waitForTimeout(300);
    await featured.focus();
    await featured.press('Enter');
    await page.waitForTimeout(650);
    assert.equal(await page.locator('.file-preview').evaluate(el => el.open), true);
    await page.keyboard.press('Escape');
    await page.waitForTimeout(350);
    assert.equal(await featured.evaluate(el => document.activeElement === el), true, '关闭后焦点返回文件');
    await page.locator('.motion-toggle').click();
    await featured.press('Enter');
    assert.equal(await page.locator('.file-preview').evaluate(el => el.getAnimations().length), 0, '暂停时预览仍可操作但无变形动画');
    await page.keyboard.press('Escape');
    await page.locator('.motion-toggle').click();
    for (const width of [320, 390, 768, 1024, 1440]) {
      await page.setViewportSize({ width, height: 900 });
      await page.waitForTimeout(50);
      assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true, `动态缩放无溢出 ${width}`);
    }
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await page.setViewportSize({ width: 390, height: 844 });
    await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' }));
    await page.waitForTimeout(100);
    await featured.focus();
    await featured.press('Enter');
    assert.equal(await page.locator('.file-preview').evaluate(el => el.getAnimations().length), 0);
    await page.screenshot({ path: `${output}/mobile-preview.png` });
    await page.keyboard.press('Escape');
    await page.locator('.constellation').scrollIntoViewIfNeeded();
    await page.locator('.constellation-hub').click();
    await page.screenshot({ path: `${output}/mobile-graph.png` });
    assert.equal(await page.locator('.graph-signal').first().isVisible(), false);
    assert.deepEqual(errors, []);

    // 真实触摸输入：文件点击、星图拖动、舞台空白处纵向滑动。
    const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, hasTouch: true, isMobile: true });
    mobile.on('pageerror', error => errors.push(error.message));
    await mobile.goto(url);
    await mobile.waitForTimeout(1700);
    const fileBox = await mobile.locator('.file-slot-featured .file-open').boundingBox();
    await mobile.touchscreen.tap(fileBox.x + fileBox.width / 2, fileBox.y + fileBox.height / 2);
    await mobile.waitForTimeout(650);
    assert.equal(await mobile.locator('.file-preview').evaluate(el => el.open), true);
    await mobile.locator('.preview-close').tap();
    await mobile.waitForTimeout(350);
    await mobile.locator('.constellation').scrollIntoViewIfNeeded();
    await mobile.waitForTimeout(900);
    const touchNode = mobile.locator('[data-node="project"]');
    const touchBefore = await touchNode.evaluate(el => el.style.left);
    const touchBox = await touchNode.boundingBox();
    const session = await mobile.context().newCDPSession(mobile);
    const x = touchBox.x + touchBox.width / 2, y = touchBox.y + touchBox.height / 2;
    await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] });
    await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x + 28, y: y + 20 }] });
    await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
    assert.notEqual(await touchNode.evaluate(el => el.style.left), touchBefore, '手机真实触摸可拖动节点');
    const scrollBefore = await mobile.evaluate(() => window.scrollY);
    await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: 10, y: 650 }] });
    await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: 10, y: 350 }] });
    await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
    await mobile.waitForTimeout(200);
    assert.ok(await mobile.evaluate(() => window.scrollY) > scrollBefore, '非节点区域正常滚动');
    await mobile.close();
    assert.deepEqual(errors, []);
    console.log('通过：文件聚拢/展开、源卡片放大预览、前后切换、联动场景、滑块定位、原弹窗/导出、节点点击/拖动/越界释放/键盘/重置、全部点亮、焦点返回、暂停与减少动态效果、五种宽度、真实触控文件打开与星图拖动、触屏正常滚动。');
  } finally {
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
